{"nbformat":4,"nbformat_minor":0,"metadata":{"colab":{"provenance":[],"gpuType":"T4","authorship_tag":"ABX9TyPTLgHxz33c83DOI95fadCs"},"kernelspec":{"name":"python3","display_name":"Python 3"},"language_info":{"name":"python"},"accelerator":"GPU","gpuClass":"standard"},"cells":[{"cell_type":"code","execution_count":6,"metadata":{"id":"SVGBZOids6gL","executionInfo":{"status":"error","timestamp":1684698769361,"user_tz":180,"elapsed":8,"user":{"displayName":"Felipe C. de Pauli","userId":"16269121212587850369"}},"colab":{"base_uri":"https://localhost:8080/","height":339},"outputId":"c8c4d5bc-05a8-4b4c-eeba-7b95f1c75842"},"outputs":[{"output_type":"error","ename":"ModuleNotFoundError","evalue":"ignored","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)","\u001b[0;32m<ipython-input-6-d08144b532a5>\u001b[0m in \u001b[0;36m<cell line: 5>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mcv2\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mcv\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdlib\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mface_recognition\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'face_recognition'","","\u001b[0;31m---------------------------------------------------------------------------\u001b[0;32m\nNOTE: If your import is failing due to a missing package, you can\nmanually install dependencies using either !pip or !apt.\n\nTo view examples of installing some common dependencies, click the\n\"Open Examples\" button below.\n\u001b[0;31m---------------------------------------------------------------------------\u001b[0m\n"],"errorDetails":{"actions":[{"action":"open_url","actionText":"Open Examples","url":"/notebooks/snippets/importing_libraries.ipynb"}]}}],"source":["import numpy as np\n","import pandas as pd\n","import cv2 as cv\n","import dlib\n","import face_recognition"]},{"cell_type":"code","source":["print(\"Is there CUDA support?:\", dlib.DLIB_USE_CUDA)\n","print(\"Dlib version\", dlib.__version__)\n","print(\"face_recognition.__version__\", fa)"],"metadata":{"colab":{"base_uri":"https://localhost:8080/"},"id":"ORnxCKc3tCRa","executionInfo":{"status":"ok","timestamp":1684698743519,"user_tz":180,"elapsed":773,"user":{"displayName":"Felipe C. de Pauli","userId":"16269121212587850369"}},"outputId":"ce42800e-9aba-454b-9121-df79a64bea8e"},"execution_count":5,"outputs":[{"output_type":"stream","name":"stdout","text":["Is there CUDA support?:  True\n","Dlib version 19.24.1\n"]}]},{"cell_type":"code","source":[],"metadata":{"id":"u1HrqkN_tPNZ"},"execution_count":null,"outputs":[]}]}